### ISSUE TITLE
ukol_01

### ISSUE THREAD

**Issue by Prymsova** [Prymsova/python-kurz-2022#1]
https://github.com/Prymsova/python-kurz-2022/blob/main/ukol_01.py

Ahoj Ondro, odevzdávám úkol.
Otázky nemám, zakládám Issue, abych si vyzkoušela kompletně zadání pro odevzdávání ;-) Užij si neděli, ahoj.

**Comment by pixelneo** [comment]
Ahoj, ukol je spravne.
Mala poznamka..  `baliky[c_baliku] == True` by slo zkratit na `baliky[c_baliku]`, ale je to detail.
