### ISSUE TITLE
úkol 3 (SMS brána)

### ISSUE THREAD

**Issue by Prymsova** [Prymsova/python-kurz-2022#3]
https://github.com/Prymsova/python-kurz-2022/blob/main/ukol_03.py

Ahoj Ondro, odevzdávám třetí úkol. Díky za všechny podněty ke zlepšení (i v těch předešlých úkolech). A.

**Comment by pixelneo** [comment]
Ahoj, neni zac :-)

Neni uplne to spravne (ac to mozna funguje). Ukolem je vytvorit dve funkce. Jedna ma overit jestli je cislo spravne a vratit tedy True/False. Druha spocitat cenu zpravy a vratit tedy int nebo float.

Obecne, je vhodne psat funkce tak aby pouze ty hodnoty vracely a `print` zavolat teprve na vracenou hodnotu. Duvodem je to, ze casto prave s tou hodnotou chces neco delat (ulozit do databaze, nekam posla, neco dalsiho spocitat, ...).

Potom taky bych doporucoval napsat ty dve funkce "na stejnou uroven" (=nevnorovat je do sebe), protoze treba by nekdo chtel spocitat cenu te SMS i kdyby nemel telefonni cislo.
(Nekdy se to dela tak, ze funkce "obsahuje" dalsi funkci, ale spise vyjimecne - cili, pokud vahas, tak je lepsi je napsat na stejnou uroven).

**Comment by Prymsova** [comment]
Ahoj, nahrála jsem druhou upravenou verzi úkolu 3 (sms brána).
https://github.com/Prymsova/python-kurz-2022/blob/main/ukol_03.py

nenapadlo mě tam nechat původní.. snad nevadí.. Mrkni, jestli je to tak, jak to bylo myšleno. Přiznám se, že mi trochu uniká podstata toho "return" (kdy to použít, kdy ne)... A.

**Comment by pixelneo** [comment]
Ahoj, v pohode. Ale porad to neni spravne, zkus si jeste precist zadani...

Pokusim se vysvetlit `return`. Chce si udelat nejakou funkci ktere predas nejaky vstup (cislo, text, ... cokoliv), ta funkce neco spocita, vytvori, upravi text, atd. a pak ten vysledek toho ci udelala vrati (`return`).

Ano, v nasem pripade kdyz udela rovnou `print` tak to taky funguje. Ovsem velmi casto ten vysledek funkce vypsat nechces. 
Napriklad, udelas si funkci (`mala_pismena(s: str)`) ktera dostane text knihy a prevede kazde velke pismeno na male (A->a, B->b, ...). A s tim vyslednym textem chces nejak pracovat - napr. ho predat dalsi funkci, ktera udela neco jineho, nebo ho klidne jen ulozit do souboru 
**nebo** pokazde neco jineho - funkci pouzijes na vice mistech (tohle je nejcastejsi pripad). A abys tu funkci mohla vyuzit vicekrat, je potreba aby tu vyslednou hodnotu vratila (`return`) a ne rovnou s ni neco udelala (`print` nebo zapis do souboru, ...)

Taky (jak jsem psal minule), funkce se definuji (az na vyjimky) na stejne urovni:
```
def je_cislo_platne(telefonni_cislo):
    # overi jestli je cislo platne a vrati True nebo False
    ...

def vypocti_celkovou_cenu_sms(celkova_delka, cena_za_180_znaku):
    # vypocita a vrati celkovou cenu
    ...
    return celkova_cena


# zbytek programu
# vsechny volani print() budou az tady
````

Cili `return` chces pouzit ve funkci skoro vzdy, krome situaci, kdy funkce pouze neco zmeni - treba do existujiciho listu prida dalsi prvek (tj. funkce upravi nejaky objekt, ktery je definovany mimo telo dane funkce - nekde 'venku').

Kdyztak napis pokud neco neni jasne. 
Ondra

**Comment by Prymsova** [comment]
Díky! Tohle vysvětlení mi pomohlo, teda doufám :-D však uvidíš na další verzi úkolu... Dostanu se k tomu ale asi až v pondělí. Dám vědět.

**Comment by Prymsova** [comment]
Ahoj, tak jsem si pustila lekci s funkcemi znovu, protože mi ty návratové hodnoty prostě nějak nedávaly smysl :-D Zkusila jsem to znovu. Teď už si myslím jsem líp pochopila smysl těch return, ale nevím, zda to volání funkcí (jedno v podmínce a jedno v printu) je tak, jak by to mělo být...? Díky za tvou trpělivost :-)

**Comment by pixelneo** [comment]
Ahoj, rekl bych, ze to je spravne :-) 
Funkci muzes volat i v podmince nebo v printu nebo si to muzes ulozit do promenne, napr:
` cena_zpravy = vypocet_ceny_zpravu(text)`
a pak uz pracovat s tou promennou.

Mej se. :-) 
Kdyztak napis, kdyby neco nebylo jasne.
