### ISSUE TITLE
úkol 4, bez bonusu

### ISSUE THREAD

**Issue by Prymsova** [Prymsova/python-kurz-2022#5]
Ahoj Ondro,
úkol 4 odevzdán zde:
https://github.com/Prymsova/python-kurz-2022/blob/main/ukol_04.py

je to verze bez bonusu, pro jistotu, abys mě zavčasu varoval, pokud mám něco blbě (trauma z 3. úkolu na funkce :-D ). Díky. Anča

P.S. A samozřejmě se děsně omlouvám, že mám takové zpoždění s úkoly :-(

**Comment by pixelneo** [comment]
Ahoj Ančo,
Trida `Auto` vypada dobre. :-) 

Ta funkce (`lze_pujcit_auto`) uz moc ne (ale ta nebyla soucastni zadani, takze ukol povazuji za dokonceny).

K tem funkcim... (budu zjednodusovat, to co napisu neplati ve 100% pripadu, ale je dobre se toho drzet):
- Funkce by nemela cist promenne definovane mimo ni, pouze ty ktere jsou predane jako argument. V tomto pripade by teda funkce `lze_pujcit_auto` nemela pouzivat `chce_auto`, `auto1`, `auto2`. 
- Pokud chces aby ta funkce pracovala s promennou treba `chce_auto` tak ji predej jako parametr:
```
def lze_pujcit_auto(znacka_kterou_chce):
    if znacka_kterou_chce == 'skoda':
        print('chce skoda auto')

chce_auto = 'skoda'
lze_pujcit_auto(chce_auto)
``` 
stejne tak lze predat promenne `auto1`, `auto2`.

- Obecne muze byt prehlednejsi funkce a tridy definovat na zacatku souboru. A pak ostatni kod (ktery ty funkce treba pouziva) pak psat pod to:
```
# definice vsech funkci a trid
# --- pomyslny oddelovac
# zbytek kodu - vytvoreni `auto1`, `auto2`, volani funkci ...
```
- Mozna pomuze si predstavit, ze tvou funkci pouziva nekdo jiny (jako ty pouzivat treba zaokrouhlovaci funci `round()`). Ta funkce `round` taky nepredpoklada ze mas nekde promennou `cislo=10.5`, jejiz hodnota by se mela zaokrouhlit, ale je nutne to tu hodnotu, nebo promennou predat jako argument: `round(cislo)` nebo rovnou `round(10.5)`.
- Stejne tak je casto vhodnejsi vysledek funkce vratit (`return`) misto rovnou zobrazit (`print`) - jako funkce `round`,  ta zakrouhlenou hodnotu vrati a da se s ni dal pracovat. V pripade funkce `lze_pujcit_auto` to mozna neni potreba, a staci ten `print` protoze vime, ze chce jen neco zobrazit.

Kdyby to nebylo jasne, klidne si muzem zavolat. ;-) 

(jinak, pro me bylo takdy tezke pochopit funkce, zadny stres, casem to pujde :-))

Mej se, 
Ondra
