### ISSUE TITLE
odevzdán úkol 8

### ISSUE THREAD

**Issue by Prymsova** [Prymsova/python-kurz-2022#8]
Ahoj, odevzdala jsem 8. úkol:
https://github.com/Prymsova/python-kurz-2022/blob/main/ukol_08.py

Nejsem si jistá, zda se to nedalo udělat nějak elegantněji, tak budu ráda za tipy na vylepšení. Anča

**Comment by pixelneo** [comment]
Ahoj Ančo,
podle me je to perfektni. :-)

Diky,
Mej se
