### ISSUE TITLE
odevzdán úkol 9, dotaz

### ISSUE THREAD

**Issue by Prymsova** [Prymsova/python-kurz-2022#9]
Ahoj, odkaz na 9. úkol:
https://github.com/Prymsova/python-kurz-2022/blob/main/ukol_09.py

Vše mi tam funguje jak má, ale mám dotaz k tomu seřazení abecedně - na první pohled mi přišlo, že je vše ok, ale když jsem udělala poslední příkaz pro výpis želv, tak jsem si všimla, že ta přídavná jména abecedně nejsou (tedy že se abecedně seřadila zvířata od Achatiny po Želvy, ale už ne v rámci želv a jejich přídavných jmen). Je to standardní chování, nebo to lze ještě nějak lépe ošetřit? Díky!

Anča

**Comment by pixelneo** [comment]
Ahoj jo, ono to radi podle "kodu" znaku (kod znaku muzes ziskat takto, napr. pro `'a'`: `ord('a')`). 
Velka pismena anglicke abecedy maji nizsi hodnoty kodu nez mala pismena a ceska pismena s diakritikou ty maji vysoke hodnoty.
Osetrit to lze tak, ze pro ucely trideni prevedes tridene stringy na jinou hodnotu: napriklad na mala pismena (to teda nevyresi tu diakritiku, ta by sla vyresit treba odstranenim diakritiky: č->c):
```
def prevod(text):
    return slovo.lower()

zvirata2 = zvirata2.sort_index(key=prevod)
```
kde v te funkci `prevod` muzes udelat jakoukoliv transformaci na aktualni hodnotu "bunky" v tom DataFramu.

Jinak ok, 
Mej se,
Ondra
